Repository team-xquare/xquare-design-system-android, pull requests merged in 2023-08, with the labels that each got.

#19 🔀 :: (#18) dynamic color 버그 수정
  xquare-design-system-android/src/main/res/values-night/themes.xml
  xquare-design-system-android/src/main/res/values/frame_margin.xml
  xquare-design-system-android/src/main/res/values/styles_typography.xml
  xquare-design-system-android/src/main/res/values/themes.xml
Labels: 리팩토링, 버그

#21 🔀 :: (#20) 아이콘 추가
  xquare-design-system-android/src/main/res/drawable/ic_filled_arrow_down.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_arrow_left.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_arrow_right.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_arrow_up.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_calendar.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_checklist_rtl.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_comment.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_dashboard.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_dropdown.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_eye.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_feed.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_gear.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_heart.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_home.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_menu.xml
  xquare-design-system-android/src/main/res/drawable/ic_filled_xquare.xml
  xquare-design-system-android/src/main/res/drawable/ic_outlined_calendar.xml
  xquare-design-system-android/src/main/res/drawable/ic_outlined_checklist_ltr.xml
  xquare-design-system-android/src/main/res/drawable/ic_outlined_dashboard.xml
  xquare-design-system-android/src/main/res/drawable/ic_outlined_eye.xml
  xquare-design-system-android/src/main/res/drawable/ic_outlined_feed.xml
  xquare-design-system-android/src/main/res/drawable/ic_outlined_heart.xml
  xquare-design-system-android/src/main/res/drawable/ic_outlined_home.xml
Labels: 기능 추가

#28 🔀 :: (#27) customview 인터페이스 패키지 이동
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/common/InitializableDrawable.kt
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/common/InitializableView.kt
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/common/Typable.kt
Labels: 리팩토링

#30 🔀 :: (#29) image button enabled 버그 수정
  app/src/main/res/layout/fragment_button.xml
  app/src/main/res/values/strings.xml
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XButton.kt
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/button/XIconButton.kt
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/util/CustomViewUtil.kt
  xquare-design-system-android/src/main/res/values/attrs.xml
  xquare-design-system-android/src/main/res/values/styles_button.xml
Labels: 리팩토링

#15 🔀 :: (#13) chip icon chip 구현
  app/src/main/res/layout/fragment_button.xml
  app/src/main/res/layout/fragment_chip.xml
  app/src/main/res/values/strings.xml
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XChip.kt
  xquare-design-system-android/src/main/kotlin/com/xquare/xdsandroid/chip/XIconChip.kt
  xquare-design-system-android/src/main/res/drawable/bg_chip_filled_enabled.xml
  xquare-design-system-android/src/main/res/drawable/bg_chip_outlined_enabled.xml
  xquare-design-system-android/src/main/res/drawable/bg_chip_text_enabled.xml
  xquare-design-system-android/src/main/res/drawable/ic_sample_16.xml
  xquare-design-system-android/src/main/res/drawable/ic_sample_24.xml
  xquare-design-system-android/src/main/res/values/attrs.xml
  xquare-design-system-android/src/main/res/values/dimens_padding.xml
  xquare-design-system-android/src/main/res/values/styles_chip.xml
Labels: 기능 추가

#39 🔀 :: (#38) chip layout divider 네이밍 수정
  app/src/main/res/layout/fragment_chip.xml
Labels: 버그
